<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenContenidoFormatoSecundarioRepository extends EntityRepository {
    
    public function listaDql() {        
        $dql   = "SELECT cfs FROM BrasaGeneralBundle:GenContenidoFormatoSecundario cfs WHERE cfs.codigoContenidoFormatoSecundarioPk <> 0";        
        $dql .= " ORDER BY cfs.codigoContenidoFormatoSecundarioPk";
        return $dql;
    }
}