<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenDirectorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenDirectorioRepository extends EntityRepository {
    
    public function agruparordenardirectorios($codigoDirectorioPadre) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT d FROM BrasaGeneralBundle:GenDirectorio d "
                . " WHERE d.codigoDirectorioPk <= ". $codigoDirectorioPadre;
                //. " GROUP BY d.codigoDirectorioPadre";
        $query = $em->createQuery($dql);        
        $breadCrumb = $query->getResult();
        return $breadCrumb;
    }
}