<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenAsesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenFestivoRepository extends EntityRepository
{
    public function festivos($fechaDesde, $fechaHasta) {
        $em = $this->getEntityManager();
        $dql   = "SELECT f.fecha FROM BrasaGeneralBundle:GenFestivo f "
                . "WHERE f.fecha >= '" . $fechaDesde . "' AND f.fecha <= '" . $fechaHasta . "'";
        $query = $em->createQuery($dql);
        $arFestivo = $query->getResult();      
        return $arFestivo;
    }    
}