<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTerceroRepository extends EntityRepository
{
    public function ListaDQL($strNombre = "", $strNit = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT t FROM BrasaGeneralBundle:GenTercero t WHERE t.codigoTerceroPk <> 0";
        if($strNombre != "" ) {
            $dql .= " AND t.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        if($strNit != "" ) {
            $dql .= " AND t.nit LIKE '%" . $strNit . "%'";
        }
        $dql .= " ORDER BY t.nombreCorto";
        return $dql;
    }    
}