<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DireccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTercerosDireccionesRepository extends EntityRepository
{
    public function DevDireccionesTercero($codigoTerceroFk)
    {
        $em = $this->getEntityManager();
        $arDirecciones = new \zikmont\FrontEndBundle\Entity\GenTercerosDirecciones();
        $arDirecciones = $em->getRepository('zikmontFrontEndBundle:GenTercerosDirecciones')->findBy(array('codigoTerceroFk' => $codigoTerceroFk));
        
        return $arDirecciones;
    }
}