<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTareaRepository extends EntityRepository
{
    
    public function listaDql($usuario = "", $estadoTerminado = "") {
        $dql   = "SELECT t FROM BrasaGeneralBundle:GenTarea t WHERE t.usuarioTareaFk = '" . $usuario . "'";        
        if($estadoTerminado == 1 ) {
            $dql .= " AND t.estadoTerminado = 1";
        }
        if($estadoTerminado == "0") {
            $dql .= " AND t.estadoTerminado = 0";
        }          
        return $dql;
    }    
    
    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if(count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {                
                $arTarea = $em->getRepository('BrasaGeneralBundle:GenTarea')->find($codigo);
                if($arTarea->getEstadoTerminado() == 0) {
                    
                }
            }
            $em->flush();
        }
    }    
}