<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvCierresMesLotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvCierresMesLotesRepository extends EntityRepository
{
    public function AsigarDatosLotesCierreALotes ($intCodigoCierreMes, $intCodigoItem) {
        $em = $this->getEntityManager();
        $arCierreMesLotes = new \Brasa\InventarioBundle\Entity\InvCierresMesLotes();
        $arCierreMesLotes = $em->getRepository('BrasaInventarioBundle:InvCierresMesLotes')->findBy(array('codigoCierreMesFk' => $intCodigoCierreMes, 'codigoItemFk' => $intCodigoItem));
        foreach ($arCierreMesLotes as $arCierreMesLotes) {
            $arLoteAct = new \Brasa\InventarioBundle\Entity\InvLotes();
            $arLoteAct = $em->getRepository('BrasaInventarioBundle:InvLotes')->find(array('codigoItemFk' => $arCierreMesLotes->getCodigoItemFk(), 'codigoBodegaFk' => $arCierreMesLotes->getCodigoBodegaFk(), 'loteFk' => $arCierreMesLotes->getLoteFk()));                            
            if(count($arLoteAct) > 0) {
                $arLoteAct->setExistencia($arCierreMesLotes->getExistencia());
            }
            $em->persist($arLoteAct);
            $em->flush();
        }        
    }
}