<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvDocumentosRepository extends EntityRepository
{
    public function DevDocumentos()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('d.codigoDocumentoPk,d.nombreDocumento')
                ->from('BrasaInventarioBundle:InvDocumentos', 'd')
                ->orderBy('d.nombreDocumento');

        $objQuery = $query->getQuery();
        $arDocumentos = new \Brasa\InventarioBundle\Entity\InvDocumentos();
        $arDocumentos = $objQuery->getResult();
        
        return $arDocumentos;
    }
}