<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvDocumentoRepository extends EntityRepository
{
    public function listaDql($codigoTipoDocumento = '', $strCodigo = '', $strNombre = '') {
        $dql   = "SELECT d FROM BrasaInventarioBundle:InvDocumento d WHERE d.codigoDocumentoPk <> 0 ";
        if($strNombre != "" ) {
            $dql .= " AND d.nombre LIKE '%" . $strNombre . "%'";
        }
        if($strCodigo != "" ) {
            $dql .= " AND d.codigoDocumentoPk LIKE '%" . $strCodigo . "%'";
        }
        if($codigoTipoDocumento != '') {
            $dql .= " AND d.codigoDocumentoTipoFk = " . $codigoTipoDocumento;
        }
        $dql .= " ORDER BY d.codigoDocumentoPk";
        return $dql;
    }
        
}