<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvDocumentoRepository extends EntityRepository
{
    public function listaDql() {
        $dql   = "SELECT d FROM BrasaInventarioBundle:InvDocumento d WHERE d.codigoDocumentoPk <> 0";
        $dql .= " ORDER BY d.codigoDocumentoPk";
        return $dql;
    }
        
}