<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvItemRepository extends EntityRepository {

    public function listaDql($strNombre = "", $strCodigo = "") {
        $dql   = "SELECT i FROM BrasaInventarioBundle:InvItem i WHERE i.codigoItemPk <> 0";        
        if($strCodigo != "") {
            $dql .= " AND i.codigoItemPk = " . $strCodigo;
        }
        if($strNombre != "") {
            $dql .= " AND i.nombre like '%" . $strNombre. "%'";
        }
        $dql .= " ORDER BY i.nombre ASC";
        return $dql;
    } 
    
    
}