<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListasPreciosDetallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvListaPrecioDetalleRepository extends EntityRepository
{
    public function DevPrecio($codigoTercero, $codigoItem) {
        $em = $this->getEntityManager();   
        $douPrecio = 0;
        $arTercero = new \Brasa\GeneralBundle\Entity\GenTercero();
        $arTercero = $em->getRepository('BrasaGeneralBundle:GenTercero')->find($codigoTercero);
        $query = $em->createQueryBuilder()            
            ->select('lpd.precio')                
            ->from('BrasaInventarioBundle:InvListaPrecioDetalle', 'lpd')
            ->where('lpd.codigoListaPreciosFk = :codigoListaPreciosFk AND lpd.codigoItemFk = :codigoItemFk')            
            ->setParameter('codigoListaPreciosFk', $arTercero->getCodigoListaPrecioFk())               
            ->setParameter('codigoItemFk', $codigoItem)
            ->getQuery();
        $arListasPreciosDetalles = $query->getResult();
        if(count($arListasPreciosDetalles) > 0)
            $douPrecio = $arListasPreciosDetalles[0]['precio'];        
        return $douPrecio;
    }    
}