<?php

namespace Brasa\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvMarcaRepository extends EntityRepository
{
    public function listaDql($strNombre = "", $strCodigo = "") {
        $dql   = "SELECT m FROM BrasaInventarioBundle:InvMarca m WHERE m.codigoMarcaPk <> 0";        
        if($strCodigo != "") {
            $dql .= " AND m.codigoMarcaPk = " . $strCodigo;
        }
        if($strNombre != "") {
            $dql .= " AND m.nombre like '%" . $strNombre. "%'";
        }
        $dql .= " ORDER BY m.nombre ASC";
        return $dql;
    }     
}