<?php

namespace Brasa\CarteraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarNotaCreditoConceptoRepository extends EntityRepository
{
    public function ListaDql($strNombre = "", $strCodigo = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT ncc FROM BrasaCarteraBundle:CarNotaCreditoConcepto ncc WHERE ncc.codigoNotaCreditoConceptoPk <> 0";
        if($strNombre != "" ) {
            $dql .= " AND ncc.nombre LIKE '%" . $strNombre . "%'";
        }
        if($strCodigo != "" ) {
            $dql .= " AND ncc.codigoNotaCreditoConceptoPk LIKE '%" . $strCodigo . "%'";
        }
        $dql .= " ORDER BY ncc.nombre";
        return $dql;
    }            
    
    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if(count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {
                $ar = $em->getRepository('BrasaCarteraBundle:CarNotaCreditoConcepto')->find($codigo);
                $em->remove($ar);
            }
            $em->flush();
        }
    } 
}