<?php

namespace Brasa\SeguridadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegAccesoUsuarioRepository extends EntityRepository {

    public function acceso($codigoUsuario, $codigoAcceso) {
        $em = $this->getEntityManager();
        $boolPermiso = false;
        $arAccesoUsuario = new \Brasa\SeguridadBundle\Entity\SegAccesoUsuario();
        $arAccesoUsuario = $em->getRepository('BrasaSeguridadBundle:SegAccesoUsuario')->findOneBy(array('codigoUsuarioFk' => $codigoUsuario, 'codigoAccesoFk' => $codigoAcceso));
        if(count($arAccesoUsuario) > 0) {
            if($arAccesoUsuario->getPermitir() == 1) {
                $boolPermiso = true;
            }
        }        
        return $boolPermiso;        
    }
}