<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurGrupoFacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurGrupoFacturacionRepository extends \Doctrine\ORM\EntityRepository
{
}
