<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsientosDetallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbAsientoDetalleRepository extends EntityRepository
{
    public function DevNroDetallesAsiento($codigoAsiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('COUNT(ad.codigoAsientoDetallePk) as cantidad')
                ->from('BrasaContabilidadBundle:CtbAsientosDetalles', 'ad')
                ->where('ad.codigoAsientoFk = :codigoAsientoFk')                
                ->setParameter('codigoAsientoFk', $codigoAsiento)
                ->getQuery();
        
        $arAsientoDetalles = $query->getResult();
        return $arAsientoDetalles[0]['cantidad'];
    }        
}