<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CtbControlRetencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbControlRetencionRepository extends EntityRepository
{
    public function DevControlRetenciones() {
        $objRepositorio = $this->getEntityManager()->getRepository('BrasaContabilidadBundle:CtbControlRetencion');    
        $objQuery = $objRepositorio->createQueryBuilder('cr')
                ->orderBy('cr.codigoTerceroFk')
                ->addOrderBy('cr.annio')
                ->addOrderBy('cr.mes');        
        
        $objQuery = $objQuery->getQuery();        
        return $objQuery->getResult();
    }      
}