<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasContablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbCuentaContableRepository extends EntityRepository
{
    /**
     * Busca los productos que coincida con la descripcion enviada con el parametro
     * @param string $strDescripcion La descripcion del producto a buscar
     * @return query el resultado de la busqueda. 
     */
    public function BuscarDescripcionCuenta($strDescripcion) {
        try {
            $strDescripcion = str_replace(" ", "%", $strDescripcion);
            
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder()
                    ->select('cuenta')
                    ->from('BrasaContabilidadBundle:CtbCuentaContable', 'cuenta')
                    ->where($em->createQueryBuilder()->expr()->like('cuenta.nombreCuenta', $em->createQueryBuilder()->expr()->literal('%' . $strDescripcion . '%')))
                    ->orWhere($em->createQueryBuilder()->expr()->like('cuenta.codigoCuentaPk', $em->createQueryBuilder()->expr()->literal('%' . $strDescripcion . '%')))
                    ->getQuery();
            $arResultado = $query->getResult();
            return $arResultado;
        } catch (Exception $e) {
            return $e;
        }
    }
}