<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CtbMovimientosTiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbMovimientosTiposRepository extends EntityRepository
{
    public function DevConsecutivo ($intCodigoMovimientoTipo) {
        $em = $this->getEntityManager();
        $arMovimientoTipo = new \Brasa\ContabilidadBundle\Entity\CtbMovimientosTipos();
        $arMovimientoTipo = $em->getRepository('BrasaContabilidadBundle:CtbMovimientosTipos')->find($intCodigoMovimientoTipo);
        $intNroDocumento = $arMovimientoTipo->getConsecutivo();
        $arMovimientoTipo->setConsecutivo($intNroDocumento + 1);
        $em->persist($arMovimientoTipo);
        $em->flush();
        return $intNroDocumento;
    }
}