<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CtbRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbRegistroExportarRepository extends EntityRepository
{

    public function listaDql($boolExportado = "") {        
        $dql   = "SELECT r FROM BrasaContabilidadBundle:CtbRegistro r WHERE r.codigoRegistroPk <> 0";
        if($boolExportado == "0") {
            $dql .= " AND r.exportado = 0";
        }
        return $dql;
    }               
}