<?php

namespace Brasa\ContabilidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CtbTerceroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbTerceroRepository extends EntityRepository {
    
    public function ListaDql($strNombre = "", $strCodigo = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT t FROM BrasaContabilidadBundle:CtbTercero t WHERE t.codigoTerceroPk <> 0";
        if($strNombre != "" ) {
            $dql .= " AND t.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        if($strCodigo != "" ) {
            $dql .= " AND t.codigoTerceroPk LIKE '%" . $strCodigo . "%'";
        }
        $dql .= " ORDER BY t.nombreCorto";
        return $dql;
    }
       
}