UPDATE rhu_examen SET codigo_factura_fk = NULL;
UPDATE rhu_seleccion SET codigo_factura_fk = NULL;

/*Afiliacion*/
DELETE FROM afi_pago_curso_detalle_curso;
DELETE FROM afi_pago_curso;
DELETE FROM afi_factura_detalle;
DELETE FROM afi_factura_detalle_curso;
DELETE FROM afi_factura;
DELETE FROM afi_periodo_detalle_pago;
DELETE FROM afi_periodo_detalle;
DELETE FROM afi_periodo;
DELETE FROM afi_curso_detalle;
DELETE FROM afi_curso;

/*Cartera*/
DELETE FROM car_recibo_detalle;
DELETE FROM car_recibo;
DELETE FROM car_nota_credito_detalle;
DELETE FROM car_nota_credito;
DELETE FROM car_nota_debito_detalle;
DELETE FROM car_nota_debito;
DELETE FROM car_cuenta_cobrar;
DELETE FROM car_cliente;

/*Turnos*/
DELETE FROM tur_simulacion_detalle;
DELETE FROM tur_novedad;
DELETE FROM tur_costo_recurso;
DELETE FROM tur_cierre_mes_servicio_detalle;
DELETE FROM tur_cierre_mes_servicio;
DELETE FROM tur_soporte_pago_detalle;
DELETE FROM tur_soporte_pago_inconsistencia;
DELETE FROM tur_soporte_pago;
DELETE FROM tur_soporte_pago_periodo;
DELETE FROM tur_factura_detalle;
DELETE FROM tur_factura_detalle_concepto;
DELETE FROM tur_factura;
DELETE FROM tur_programacion_detalle;
DELETE FROM tur_programacion;
DELETE FROM tur_pedido_detalle_recurso;
DELETE FROM tur_pedido_detalle;
DELETE FROM tur_pedido;
DELETE FROM tur_servicio_detalle_plantilla;
DELETE FROM tur_servicio_detalle_recurso;
DELETE FROM tur_servicio_detalle;
DELETE FROM tur_servicio;
DELETE FROM tur_cotizacion_otro;
DELETE FROM tur_cotizacion_detalle;
DELETE FROM tur_cotizacion;
/*DELETE FROM tur_recurso;*/

/* Recurso humano */
DELETE FROM rhu_visita;
DELETE FROM rhu_provision;
DELETE FROM rhu_provision_periodo;
DELETE FROM rhu_soporte_pago_horario_detalle;
DELETE FROM rhu_soporte_pago_horario;
DELETE FROM rhu_permiso;
DELETE FROM rhu_soporte_pago_horario;
DELETE FROM rhu_horario_acceso;
DELETE FROM rhu_horario_periodo;
DELETE FROM rhu_desempeno_detalle;
DELETE FROM rhu_desempeno;
DELETE FROM rhu_capacitacion_detalle;
DELETE FROM rhu_capacitacion_nota;
DELETE FROM rhu_capacitacion;
DELETE FROM rhu_empleado_informacion_interna;
DELETE FROM rhu_seleccion_requisicion_aspirante;
DELETE FROM rhu_aspirante;
DELETE FROM rhu_embargo;
DELETE FROM rhu_requisito_detalle;
DELETE FROM rhu_requisito;
DELETE FROM rhu_supervigilancia_parafiscales;
DELETE FROM ad_archivo;
DELETE FROM rhu_pago_examen_detalle;
DELETE FROM rhu_pago_examen;
DELETE FROM rhu_pago_banco_detalle;
DELETE FROM rhu_pago_banco;
DELETE FROM rhu_proyeccion;
DELETE FROM rhu_credito_pago;
DELETE FROM rhu_ingreso_base;
DELETE FROM rhu_cambio_salario;
DELETE FROM rhu_factura_detalle;
DELETE FROM rhu_factura;
DELETE FROM rhu_sso_aporte;
DELETE FROM rhu_sso_periodo_empleado;
DELETE FROM rhu_sso_periodo_detalle;
DELETE FROM rhu_seleccion_entrevista;
DELETE FROM rhu_seleccion_referencia;
DELETE FROM rhu_seleccion_prueba;
DELETE FROM rhu_seleccion_visita;
DELETE FROM rhu_seleccion;
DELETE FROM rhu_seleccion_requisito;
DELETE FROM rhu_pago_adicional;
DELETE FROM rhu_servicio_cobrar;
DELETE FROM rhu_pago_detalle;
DELETE FROM rhu_pago;
DELETE FROM rhu_incapacidad_pago_detalle;
DELETE FROM rhu_incapacidad_pago;
DELETE FROM rhu_incapacidad;
DELETE FROM rhu_licencia;
DELETE FROM rhu_credito_pago;
DELETE FROM rhu_programacion_pago_detalle;
DELETE FROM rhu_programacion_pago;
DELETE FROM rhu_liquidacion_adicionales;
DELETE FROM rhu_liquidacion;
DELETE FROM rhu_vacacion_credito;
DELETE FROM rhu_vacacion_adicional;
DELETE FROM rhu_vacacion;
DELETE FROM rhu_contrato_sede;
DELETE FROM rhu_contrato_prorroga;
DELETE FROM rhu_traslado_salud;
DELETE FROM rhu_traslado_pension;
DELETE FROM rhu_disciplinario_descargo;
DELETE FROM rhu_disciplinario;
DELETE FROM rhu_cambio_tipo_contrato;
DELETE FROM rhu_contrato;
DELETE FROM rhu_credito;
DELETE FROM rhu_dotacion_detalle;
DELETE FROM rhu_dotacion;
DELETE FROM rhu_acreditacion;
DELETE FROM rhu_empleado_estudio;
DELETE FROM rhu_empleado_familia;
DELETE FROM rhu_accidente_trabajo;
/*DELETE FROM rhu_empleado;*/
DELETE FROM rhu_examen_restriccion_medica_detalle;
DELETE FROM rhu_examen_restriccion_medica;
DELETE FROM rhu_examen_detalle;
DELETE FROM rhu_examen;
DELETE FROM rhu_sede;
/*DELETE FROM rhu_centro_costo;*/
DELETE FROM ctb_registro;
DELETE FROM ctb_registro_exportar;

/*INSERT INTO `rhu_centro_costo` (`codigo_centro_costo_pk`, `codigo_periodo_pago_fk`, `codigo_ciudad_fk`, `codigo_sucursal_fk`, `nombre`, `fecha_ultimo_pago`, `fecha_ultimo_pago_programado`, `correo`, `codigo_interface`, `pago_abierto`, `estado_activo`, `generar_pago_automatico`, `hora_pago_automatico`, `comentarios`, `porcentaje_administracion`, `valor_administracion`, `fecha_ultimo_pago_prima`, `fecha_ultimo_pago_cesantias`, `dias_pago`, `genera_servicio_cobrar`, `codigo_usuario`, `codigo_cliente_fk`, `administrativo`, `codigo_recurso_grupo_fk`, `imprimir_programacion_formato`) VALUES('1','4','2239','1','MEDELLIN','2016-04-15','2016-09-15',NULL,NULL,'1','1','0','00:00:00',NULL,'6','0','2015-12-30','2015-12-30','15-30','0','ADMINISTRADOR',NULL,'1','0','0');
INSERT INTO `rhu_centro_costo` (`codigo_centro_costo_pk`, `codigo_periodo_pago_fk`, `codigo_ciudad_fk`, `codigo_sucursal_fk`, `nombre`, `fecha_ultimo_pago`, `fecha_ultimo_pago_programado`, `correo`, `codigo_interface`, `pago_abierto`, `estado_activo`, `generar_pago_automatico`, `hora_pago_automatico`, `comentarios`, `porcentaje_administracion`, `valor_administracion`, `fecha_ultimo_pago_prima`, `fecha_ultimo_pago_cesantias`, `dias_pago`, `genera_servicio_cobrar`, `codigo_usuario`, `codigo_cliente_fk`, `administrativo`, `codigo_recurso_grupo_fk`, `imprimir_programacion_formato`) VALUES('2','4','2387','3','BOGOTA','2015-12-30','2016-09-15',NULL,NULL,'1','1','0','00:00:00',NULL,'6','0','2015-12-30','2015-12-30','15-30','0','ADMINISTRADOR',NULL,'1','0','0');
INSERT INTO `rhu_centro_costo` (`codigo_centro_costo_pk`, `codigo_periodo_pago_fk`, `codigo_ciudad_fk`, `codigo_sucursal_fk`, `nombre`, `fecha_ultimo_pago`, `fecha_ultimo_pago_programado`, `correo`, `codigo_interface`, `pago_abierto`, `estado_activo`, `generar_pago_automatico`, `hora_pago_automatico`, `comentarios`, `porcentaje_administracion`, `valor_administracion`, `fecha_ultimo_pago_prima`, `fecha_ultimo_pago_cesantias`, `dias_pago`, `genera_servicio_cobrar`, `codigo_usuario`, `codigo_cliente_fk`, `administrativo`, `codigo_recurso_grupo_fk`, `imprimir_programacion_formato`) VALUES('3','4','3068','1','PEREIRA (OPERATIVA)','2016-04-15','2016-09-15',NULL,NULL,'1','1','0','00:00:00',NULL,'6','0','2015-12-30','2015-12-30','15-30','0','ADMINISTRADOR',NULL,'0','1','1');*/

INSERT INTO `rhu_programacion_pago` (`codigo_programacion_pago_pk`, `codigo_pago_tipo_fk`, `codigo_centro_costo_fk`, `fecha_desde`, `fecha_hasta`, `fecha_hasta_real`, `dias`, `estado_generado`, `estado_pagado`, `estado_pagado_banco`, `estado_anulado`, `verificar_pagos_adicionales`, `verificar_incapacidades`, `novedades_verificadas`, `vr_neto`, `empleados_generados`, `no_generar_periodo`, `numero_empleados`, `inconsistencias`, `codigo_usuario`) VALUES('120','1','2','2016-09-01','2016-09-15','2016-09-15','15','0','0','0','0','0','0','0','0','0','0','0','0','ADMINISTRADOR');
INSERT INTO `rhu_programacion_pago` (`codigo_programacion_pago_pk`, `codigo_pago_tipo_fk`, `codigo_centro_costo_fk`, `fecha_desde`, `fecha_hasta`, `fecha_hasta_real`, `dias`, `estado_generado`, `estado_pagado`, `estado_pagado_banco`, `estado_anulado`, `verificar_pagos_adicionales`, `verificar_incapacidades`, `novedades_verificadas`, `vr_neto`, `empleados_generados`, `no_generar_periodo`, `numero_empleados`, `inconsistencias`, `codigo_usuario`) VALUES('121','1','1','2016-09-01','2016-09-15','2016-09-15','15','0','0','0','0','0','0','0','0','0','0','0','0','ADMINISTRADOR');
INSERT INTO `rhu_programacion_pago` (`codigo_programacion_pago_pk`, `codigo_pago_tipo_fk`, `codigo_centro_costo_fk`, `fecha_desde`, `fecha_hasta`, `fecha_hasta_real`, `dias`, `estado_generado`, `estado_pagado`, `estado_pagado_banco`, `estado_anulado`, `verificar_pagos_adicionales`, `verificar_incapacidades`, `novedades_verificadas`, `vr_neto`, `empleados_generados`, `no_generar_periodo`, `numero_empleados`, `inconsistencias`, `codigo_usuario`) VALUES('122','1','3','2016-09-01','2016-09-15','2016-09-15','15','0','0','0','0','0','0','0','0','0','0','0','0','ADMINISTRADOR');

UPDATE `rhu_configuracion` SET anio_actual = 2016, vr_salario = 689455, vr_auxilio_transporte = 77700;
UPDATE `rhu_cierre_anio` SET estado_cerrado = 0;
UPDATE `rhu_sso_periodo` SET estado_generado = 0, estado_cerrado = 0;

/*INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('1','1','1','13','S','3','1','17','2','3','1','2239','2239','2239','1','1','1','1','0','2','1','1','1042150545',NULL,'AICARDO ANDRES PEREZ QUIROZ','AICARDO','ANDRES','PEREZ','QUIROZ','4410291','3147949994','CL 82  88 02','ROBLEDO VILLA SOFIA','M','AHICARDO.PEREZ@HOTMAIL.COM','1990-03-20','69385396775','S','ANALISTA','1','700000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-12','2016-09-29','0','0',NULL,'0','0','1',NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('2','1','1','13','S','3','1','17','1','3','1','2239','2239','2239','1','1','1','1','0','2','1','1','43730175',NULL,'ALBA LUCIA DUQUE MONTES','ALBA','LUCIA','DUQUE','MONTES','2366067','3176762015','CL 105 A 46 A 59','VILLA DEL SOCORRO','M','','1971-04-07','55147555473','S','ANALISTA','1','1200000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-14','2016-09-29','0','0',NULL,'0','0','2',NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('3','1','1','13','S','3','1','23','1','3','1','2239','2239','2239','1','1','1','1','0','2','4','2','1069743758','1069743758','ALBA LUZ CIFUENTES MARTINEZ','ALBA','LUZ','CIFUENTES','MARTINEZ','5302892','3143235871','CR 51 176 60','NUEVA ZELANDA','M','LAY-1805@HOTMAIL.COM','1993-05-21','58843538957','S','ANALISTA','1','900000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-02','2016-09-29','0','0',NULL,'0','0','3',NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('4','1','1','13','S','3','1','22','2','3','1','2239','2239','2239','1','1','1','1','0','2','4','2','1035831558','1035831558','ALBA NELLY LOPERA LOPERA','ALBA','NELLY','LOPERA','LOPERA','5877269','3217469353','CR 36A 66 70','VILLA HERMOSA','M','ALBALOPELOPE@HOTMAIL.COM','1992-02-25','00425179705','S','ANALISTA','1','644350','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-05','2016-09-29','0','0',NULL,'0','0','4',NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('5','1','1','13','S','3','1','24','2','3','1','2239','2239','2239','1','1','1','1','0','2','5','2','34317595','34317595','ALBA YOLIMA MARTINEZ DIAZ','ALBA','YOLIMA','MARTINEZ','DIAZ','8221495','3216195856','CR 7 17 04','BRR POPAYAN','M','YOLI8205@HOTMAIL.COM','1982-05-01','86842926205','S','ANALISTA','1','644350','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','5','5','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('6','1','1','13','S','3','1','17','1','3','1','2239','2239','2239','1','1','1','1','0','2','5','2','1036944001','1036944001','ALEJANDRA  ALZATE ALZATE','ALEJANDRA',NULL,'ALZATE','ALZATE','5797909','3205460976','CL 50  58 24','ALTO DEL MEDIO','M','ALEJA_9220@HOTMAIL.COM','1992-06-02','02443397224','S','ANALISTA','0','1350000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','6','6','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('7','1','1','13','S','3','1','22','1','3','1','2239','2239','2239','1','1','1','1','0','2','5','2','1152211998','1152211998','ALEJANDRA  ALZATE ECHEVERRY','ALEJANDRA',NULL,'ALZATE','ECHEVERRY','5219130','3015492392','CR 42 B  91 77','MANRIQUE','M','ALEJAALZATE2211@HOTMAIL.COM','1996-01-23','00120227611','S','ANALISTA','1','690000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-10','2016-09-29','0','0',NULL,'0','0','7','7','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('8','1','1','13','S','3','1','22','2','3','1','2239','2239','2239','1','1','1','1','0','2','6','2','1151946251','1151946251','ALEJANDRA  ERAZO ORDOÃƒâ€˜EZ','ALEJANDRA',NULL,'ERAZO','ORDOÃƒâ€˜EZ','6027657','3147207343','CL 35  D SUR 27 D 29','GUADACANAL','M','ALEJANDRA_ERAZO_30@HOTMAIL.COM','1992-04-30','83645446570','S','ANALISTA','1','700000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-02','2016-09-29','0','0',NULL,'0','0','8','8','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('9','1','1','13','S','3','1','17','1','3','1','2239','2239','2239','1','1','1','1','0','2','6','2','1020458677','1020458677','ALEJANDRA  ROJAS MARTINEZ','ALEJANDRA',NULL,'ROJAS','MARTINEZ','4777224','3206427493','CL 42  A 12 17','BUENOS AIRES','M','ALEXANDRA_GT@HOTMAIL.COM','1994-03-28','11111111111','S','ANALISTA','1','850000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-08','2016-09-29','0','0',NULL,'0','0','9','9','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('10','1','1','13','S','3','1','17','2','3','1','2239','2239','2239','1','1','1','1','0','2','6','2','1017206105','1017206105','ALEJANDRA MARCELA VALENCIA MARIN','ALEJANDRA','MARCELA','VALENCIA','MARIN','5277535','3116682509','CL 71B  31 31','MANRIQUE','M','LUCCIANA1003@HOTMAIL.COM','1992-09-11','51130872577','S','ANALISTA','1','644350','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','10','10','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','2','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('11','1','1','13','S','2','1','12','2','3','1','2239','2239','2239','1','1','1','1','0','2','2','2','1061654706','1061654706','ADRIANA MARIA LOPEZ AGUDELO','ADRIANA','MARIA','LOPEZ','AGUDELO','7566904','3102627934','CL 59SUR 92 A 28 CA 76','BOSA PORVENIR','M','MONASAMANA@HOTMAIL.COM','1986-08-19','04547929298','S','ANALISTA','1','700000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','11','11','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('12','1','1','13','S','2','1','17','5','3','1','2239','2239','2239','1','1','1','1','0','2','2','1','43273986','43273986','ADRIANA MARIA GALVIS CASAS','ADRIANA','MARIA','GALVIS','CASAS','3427514','3008215787','CL 6 SUR 81 B 45 AP 102','BELEN RINCON','M','rtrtrt','1981-09-03','61441381319','S','ANALISTA','1','644350','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-05','2016-09-29','0','0',NULL,'0','0','12','12','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('13','1','1','13','S','2','1','17','2','3','1','2239','2239','2239','1','1','1','1','0','2','1','1','43278943',NULL,'ADRIANA MARIA VASQUEZ GOMEZ','ADRIANA','MARIA','VASQUEZ','GOMEZ','2221108','3216375129','CL 55  7 82','CAICEDO','M','','1981-08-27','24531079252','S','ANALISTA','0','1800000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','13','13','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('14','1','1','13','S','2','1','22','2','3','1','2239','2239','2239','1','1','1','1','0','2','1','1','1128415212',NULL,'ADRIANA MILENA ARANGO MARIN','ADRIANA','MILENA','ARANGO','MARIN','2114252','3218533764','CR 38  93 39','MANRIQUE','M','','1988-05-12','36245069175','S','ANALISTA','0','1300000','1985-09-03','1','1','0',NULL,NULL,NULL,'2016-01-01','2016-09-29','0','0',NULL,'0','0','14','14','1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('20',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','71318220',NULL,'REINEL ALBERTO TABORDA LONDOÃƒâ€˜O','REINEL','ALBERTO','TABORDA','LONDOÃƒâ€˜O','2528762','3194586266','CR 102  B 48 CC 28','SAN JAVIER','M','','1980-11-25','','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('21',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1023898498',NULL,'JENNIFER JOHANA MARIN GUERRERO','JENNIFER','JOHANA','MARIN','GUERRERO','5512473','3015196572','CL 46 DSUR 15 81 ESTE','QUINDIO','M','JENNM2010@HOTMAIL.COM','1990-03-27','30044727184','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('22',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1152444554',NULL,'JOHN EDWAR GRAJALES GOMEZ','JOHN','EDWAR','GRAJALES','GOMEZ','3422204','3128895458','CL 6SUR 70 250','BELEN','M','JOHNEREX2901@HOTMAIL.COM','1993-01-29','27444286534','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('23',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1020414940',NULL,'HERNAN DARIO DUQUE CARMONA','HERNAN','DARIO','DUQUE','CARMONA','2586302','3003566145','CL 100 50 C 13','SANTA CRUZ','M','HERNAN_DUCAR@HOTMAIL.COM','1988-07-04','00133465855','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('24',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1128433215',NULL,'YEISON  VILLADA ROJAS','YEISON','','VILLADA','ROJAS','4921254','3137144490','CL 39 BB  115 12','SAN JAVIER','M','YEYOVILLADA@HOTMAIL.COM','1990-01-09','28015070244','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('25',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1040502907',NULL,'KARIN ANDRES JARAMILLO LOREO','KARIN','ANDRES','JARAMILLO','LOREO','2216090','3194603734','CL 54  17 B 72 IN 201','ENCISO VILLATINA','M','KARJALOR@HOTMAIL.COM','1990-11-15','00817087248','S',NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('26',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1020410527',NULL,'DAVID ESTEBAN CUARTAS MESA','DAVID','ESTEBAN','CUARTAS','MESA','5967696','3116179814','AV 46  59 36','NIQUIA','M','','1987-10-29','60938880321',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('27',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1152458063',NULL,'JOSE ISMAEL PARRA CASTILLO','JOSE','ISMAEL','PARRA','CASTILLO','3420305','3113261296','CL 20 DD  84 BB 88','BELEN','M','JOSE.962010@HOTMAIL.COM','1995-10-04','00742840891',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('28',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','43159816',NULL,'HILDA MILENA MESA GONZALEZ','HILDA','MILENA','MESA','GONZALEZ','4426391','3046763029','CL 78 87 69 IN 206','ROBLEDO EL DIAMANTE','M','MILENAMESA431@HOTMAIL.COM','1979-06-11','10015394867',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('29',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1000633410',NULL,'JUAN DIEGO RIOS AGUDELO','JUAN','DIEGO','RIOS','AGUDELO','4715980','3046592855','CL 106 D 82 11','12 DE OCTUBRE','M','JUAN.DIEGO.RIOS@HOTMAIL.COM','1995-01-06','51142748821',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('30',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','43267338',NULL,'ENITH DEL CARMEN ESTRELLA DIAZ','ENITH','DEL CARMEN','ESTRELLA','DIAZ','2387975','3205049717','CR 88 31 70','BELEN','M','','1977-02-11','29212981581',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('31',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1024494198',NULL,'EDNA MAGDALENA BARRETO LOZANO','EDNA','MAGDALENA','BARRETO','LOZANO','7443101','3138754029','CL 58 SUR  93 C 46','BOSA','M','EDNALABONITA1@HOTMAIL.COM','1989-02-05','',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('32',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1143857372',NULL,'MONICA  ESCOBAR QUINTERO','MONICA','','ESCOBAR','QUINTERO','1','3177240650','CR 37 A  15 29','CRISTOBAL COLON','M','MONICAESCOBAR0403@GMAIL.COM','1994-09-04','71095996421',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('33',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','1024553279',NULL,'JESSICA ALEJANDRA GOMEZ GONZALEZ','JESSICA','ALEJANDRA','GOMEZ','GONZALEZ','7758913','3218960016','CL 66 71I 09SUR','PERDOMO','M','ALEJAG142008@HOTMAIL.ES','1994-04-20','15441972790',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `rhu_empleado` (`codigo_empleado_pk`, `codigo_clasificacion_riesgo_fk`, `codigo_empleado_estudio_tipo_fk`, `codigo_tipo_identificacion_fk`, `codigo_estado_civil_fk`, `codigo_centro_costo_fk`, `codigo_banco_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_tipo_tiempo_fk`, `codigo_ciudad_fk`, `codigo_ciudad_nacimiento_fk`, `codigo_ciudad_expedicion_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_rh_fk`, `codigo_horario_fk`, `codigo_departamento_empresa_fk`, `numero_identificacion`, `libreta_militar`, `nombre_corto`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `telefono`, `celular`, `direccion`, `barrio`, `codigo_sexo_fk`, `correo`, `fecha_nacimiento`, `cuenta`, `tipo_cuenta`, `cargo_descripcion`, `auxilio_transporte`, `vr_salario`, `fecha_expedicion_identificacion`, `estado_activo`, `estado_contrato_activo`, `cabeza_hogar`, `camisa`, `jeans`, `calzado`, `fecha_contrato`, `fecha_finaliza_contrato`, `contrato_indefinido`, `pagado_entidad_salud`, `comentarios`, `horas_laboradas_periodo`, `padre_familia`, `codigo_contrato_activo_fk`, `codigo_contrato_ultimo_fk`, `ruta_foto`, `empleado_informacion_interna`, `codigo_usuario`, `codigo_interface`, `codigo_tipo_libreta`, `codigo_zona_fk`, `codigo_subzona_fk`, `codigo_empleado_tipo_fk`, `discapacidad`, `codigo_entidad_cesantia_fk`, `codigo_centro_costo_contabilidad_fk`, `dato`, `digito_verificacion`, `codigo_puesto_fk`) VALUES('34',NULL,'1','13','S',NULL,'1',NULL,NULL,NULL,NULL,'2239','2239','2239',NULL,NULL,NULL,NULL,NULL,'2','1','1','8432351',NULL,'DIEGO ANDRES GAVIRIA BAENA','DIEGO','ANDRES','GAVIRIA','BAENA','5163503','3145424169','CR 44 AA 85 37','CAMPO VALDES','M','','1980-10-30','036001172471',NULL,NULL,'1','0','1985-09-03','0','0','0',NULL,NULL,NULL,'2016-01-01','2016-01-01','0','0',NULL,'0','0',NULL,NULL,'1_IMG_6583.JPG',NULL,NULL,NULL,'0','1','1','1','0',NULL,NULL,NULL,NULL,NULL);*/


INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('1','1','1','3','1','1','1','1','1','1','0',NULL,'17','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','700000','700000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('2','2','1','3','1','1','1','1','1','1','0',NULL,'17','1','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','1200000','1200000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('3','3','1','3','1','1','1','1','1','1','0',NULL,'23','1','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','900000','900000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('4','4','1','3','1','1','1','1','1','1','0',NULL,'22','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','689455','689455','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('5','5','1','3','1','1','1','1','1','1','0',NULL,'24','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'R123','ANALISTA','HORARIO FIJO','689455','689455','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('6','6','1','3','1','1','1','1','1','1','0',NULL,'17','1','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','1350000','1350000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('7','7','1','3','1','1','1','1','1','1','0',NULL,'22','1','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','690000','690000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('8','8','1','3','1','1','1','1','1','1','0',NULL,'22','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','700000','700000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('9','9','1','3','1','1','1','1','1','1','0',NULL,'17','1','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','850000','850000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('10','10','1','3','1','1','1','1','1','1','0',NULL,'17','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'R123','ANALISTA','HORARIO FIJO','689455','689455','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('11','11','1','2','1','1','1','1','1','1','0',NULL,'12','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','700000','700000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('12','12','1','2','1','1','1','1','1','1','0',NULL,'17','5','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','689455','689455','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('13','13','1','2','1','1','1','1','1','1','0',NULL,'17','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'001','ANALISTA','HORARIO FIJO','1800000','1800000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
INSERT INTO `rhu_contrato` (`codigo_contrato_pk`, `codigo_empleado_fk`, `codigo_tipo_tiempo_fk`, `codigo_centro_costo_fk`, `codigo_contrato_tipo_fk`, `codigo_clasificacion_riesgo_fk`, `codigo_cargo_fk`, `codigo_tipo_pension_fk`, `codigo_tipo_salud_fk`, `codigo_tipo_cotizante_fk`, `codigo_subtipo_cotizante_fk`, `codigo_motivo_terminacion_contrato_fk`, `codigo_entidad_salud_fk`, `codigo_entidad_pension_fk`, `codigo_entidad_caja_fk`, `codigo_ciudad_contrato_fk`, `fecha`, `fecha_desde`, `fecha_hasta`, `fecha_prorroga_inicio`, `fecha_prorroga_final`, `numero`, `cargo_descripcion`, `horario_trabajo`, `vr_salario`, `vr_salario_pago`, `estado_activo`, `comentarios`, `indefinido`, `fecha_ultimo_pago_cesantias`, `fecha_ultimo_pago_vacaciones`, `fecha_ultimo_pago_primas`, `fecha_ultimo_pago`, `estado_liquidado`, `factor`, `factor_horas_dia`, `salario_integral`, `codigo_usuario`, `ibp_cesantias_inicial`, `codigo_salario_tipo_fk`, `codigo_ciudad_labora_fk`, `promedio_recargo_nocturno_inicial`, `estado_terminado`, `codigo_usuario_termina`, `codigo_entidad_cesantia_fk`, `ibp_primas_inicial`, `limitarHoraExtra`) VALUES('14','14','1','2','1','1','1','1','1','1','0',NULL,'22','2','3','2239','2016-09-01','2016-09-01','2017-09-01',NULL,NULL,'R123','ANALISTA','HORARIO FIJO','1300000','1300000','1',NULL,'1','2016-09-01','2016-09-01','2016-09-01','2016-09-01','0','8','8','0','marioestrada','0','1','2239','0','0',NULL,'1','0','0');
