<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuAccidenteTrabajoRepository extends EntityRepository {
   
    public function listaDql($strCodigoCentroCosto = "", $strIdentificacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT at, e FROM BrasaRecursoHumanoBundle:RhuAccidenteTrabajo at JOIN at.empleadoRel e WHERE at.codigoAccidenteTrabajoPk <> 0";
        
        if($strCodigoCentroCosto != "") {
            $dql .= " AND at.codigoCentroCostoFk = " . $strCodigoCentroCosto;
        }   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        return $dql;
    }    
    
}