<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuContratoProrrogaRepository extends EntityRepository {
    
    public function contratoProrroga($codigoContrato = "", $fechaDesde = "", $fechaHasta = "", $codigoContratoProrroga = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT cp FROM BrasaRecursoHumanoBundle:RhuContratoProrroga cp "
                ." WHERE (cp.fechaFinalNueva >= '" . date_format($fechaDesde, ('Y-m-d')) . "' "
                . "OR cp.fechaFinalNueva >= '" . date_format($fechaHasta, ('Y-m-d')) . "') "
                . "AND cp.codigoContratoFk = " . $codigoContrato . " ";
        if($codigoContratoProrroga != "" ) {
            $dql .= " AND cp.codigoContratoProrrogaPk <> " . $codigoContratoProrroga . " ";
        }
        $dql .= " ORDER BY cp.codigoContratoProrrogaPk DESC";
                //. "ORDER BY cp.codigoContratoProrrogaPk ASC";
        $query = $em->createQuery($dql);        
        $arContratoProrroga = $query->getResult();        
        return $arContratoProrroga;
    }
}