<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuContratoGrupoRepository extends EntityRepository { 
    
    public function listaDql() {        
        $dql   = "SELECT ct FROM BrasaRecursoHumanoBundle:RhuContratoTipo ct WHERE ct.codigoContratoTipoPk <> 0";        
        $dql .= " ORDER BY ct.codigoContratoTipoPk";
        return $dql;
    }       
}