<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuCapacitacionDetalleRepository extends EntityRepository {
    
    public function listaDql($strCargo = "", $strCentroCosto = "", $strIdentificacion = "", $strNombre = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT e FROM BrasaRecursoHumanoBundle:RhuEmpleado e WHERE e.codigoEmpleadoPk <> 0";
  
        if($strCargo != "") {
            $dql .= " AND e.codigoCargoFk = " . $strCargo;
        }
        if($strCentroCosto != "") {
            $dql .= " AND e.codigoCentroCostoFk = " . $strCentroCosto;
        }
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
        return $dql;
    }     
}