<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuCierreAnioRepository extends EntityRepository {
    public function listaDql() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ca FROM BrasaRecursoHumanoBundle:RhuCierreAnio ca WHERE ca.estadoCerrado = 0";
        $dql .= " ORDER BY ca.anio ASC";
        return $dql;
    }                            
    
}