<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuDesempenoDetalleRepository extends EntityRepository {
    
    public function ordenarPreguntasTipo($codigoDesempeno) {
        $em = $this->getEntityManager();
        
        $dql   = "SELECT dd, dc FROM BrasaRecursoHumanoBundle:RhuDesempenoDetalle dd JOIN dd.desempenoConceptoRel dc "
                . "WHERE dd.codigoDesempenoFk = " . $codigoDesempeno . " ORDER BY dc.codigoDesempenoConceptoTipoFk";
        $query = $em->createQuery($dql);
        $ordenarPreguntasTipo = $query->getResult();
        return $ordenarPreguntasTipo;
    }
       
}