<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuDisciplinarioRepository extends EntityRepository {
    public function listaDQL($strIdentificacion = "", $codigoCentroCosto = "") {        
        $dql   = "SELECT d, e FROM BrasaRecursoHumanoBundle:RhuDisciplinario d JOIN d.empleadoRel e WHERE d.codigoDisciplinarioPk <> 0";
        if($strIdentificacion != "" ) {
            $dql .= " AND d.codigoEmpleadoFk LIKE '%" . $strIdentificacion . "%'";
        }
        if($codigoCentroCosto != "" ) {
            $dql .= " AND e.codigoCentroCostoFk = " . $codigoCentroCosto;
        }
        $dql .= " ORDER BY d.fecha";
        return $dql;
    }       
    
    public function fechaAntigua() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT min(d.fecha) FROM BrasaRecursoHumanoBundle:RhuDisciplinario d";
        $query = $em->createQuery($dql);
        $fechaAntigua = $query->getSingleScalarResult(); 
        return $fechaAntigua;
    }
}