<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuDotacionRepository extends EntityRepository {
    
    public function listaDQL($strIdentificacion = "", $codigoCentroCosto = "") {        
        $dql   = "SELECT d, e FROM BrasaRecursoHumanoBundle:RhuDotacion d JOIN d.empleadoRel e WHERE d.codigoDotacionPk <> 0";
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        if($codigoCentroCosto != "" ) {
            $dql .= " AND e.codigoCentroCostoFk = " . $codigoCentroCosto;
        }
        $dql .= " ORDER BY d.fecha";
        return $dql;
    } 
    
    public function dotacionDevolucion($codigoEmpleado = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT dd, d FROM BrasaRecursoHumanoBundle:RhuDotacionDetalle dd JOIN dd.dotacionRel d "
                . "WHERE (dd.cantidadAsignada - dd.cantidadDevuelta) > 0 "
                . "AND d.codigoDotacionTipoFk = 1"
                . "AND d.estadoCerrado = 0"
                . "AND d.codigoEmpleadoFk = " . $codigoEmpleado;
        $query = $em->createQuery($dql);
        $arDotacionDetalle = $query->getResult();
        return $arDotacionDetalle;
    }
}