<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoEstudioRepository extends EntityRepository {
    
    public function listaDql($strIdentificacion = "", $strFecha = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ee, e FROM BrasaRecursoHumanoBundle:RhuEmpleadoEstudio ee JOIN ee.empleadoRel e WHERE ee.validarVencimiento = 1";
   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if ($strFecha != ""){
            $dql .= " AND ee.fechaVencimiento >='" . $strFecha . "'";
        }
        //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
        return $dql;
    }                 
}