<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoEstudioRepository extends EntityRepository {
    
    public function listaDql($strIdentificacion = "", $strFecha = "", $strFechaAcreditacion = "" ) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ee, e FROM BrasaRecursoHumanoBundle:RhuEmpleadoEstudio ee JOIN ee.empleadoRel e WHERE ee.validarVencimiento = 1";
   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if ($strFecha != ""){
            $dql .= " AND ee.fechaVencimientoCurso <='" . date_format($strFecha, ('Y-m-d')) . "'";
        }
        if ($strFechaAcreditacion != ""){
            $dql .= " AND ee.fechaVencimientoAcreditacion <='" . date_format($strFechaAcreditacion, ('Y-m-d')) . "'";
        }
        //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
        return $dql;
    } 
    
    public function listaMovimientoDql($strIdentificacion = "", $strNombre = "", $strEstudio = "", $strEstado = "", $fechaVencimientoControl = "", $fechaVencimientoAcreditacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ee, e FROM BrasaRecursoHumanoBundle:RhuEmpleadoEstudio ee JOIN ee.empleadoRel e WHERE ee.codigoEmpleadoEstudioPk <> 0";
   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        if($strEstudio != "") {
            $dql .= " AND ee.codigoEmpleadoEstudioTipoFk = " . $strEstudio;
        }
        if($strEstado != "") {
            $dql .= " AND ee.codigoEstudioEstadoFk = " . $strEstado;
        }       
        if($fechaVencimientoControl != "" ) {
            $dql .= " AND ee.fechaVencimientoCurso <='" . date_format($fechaVencimientoControl, ('Y-m-d')) . "'";
        }
        
        if($fechaVencimientoAcreditacion != "" ) {
            $dql .= " AND ee.fechaVencimientoAcreditacion <='" . date_format($fechaVencimientoAcreditacion, ('Y-m-d')) . "'";
        }        
        $dql .= " ORDER BY ee.codigoEmpleadoEstudioPk desc";
        return $dql;
    }
}