<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoRepository extends EntityRepository {                   
    
    public function ListaDQL($strNombre, $strCodigoCentroCosto = "", $boolMostrarActivos) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT e FROM BrasaRecursoHumanoBundle:RhuEmpleado e WHERE e.codigoEmpleadoPk <> 0";
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%" . $strNombre . "%'";
        }      
        if($strCodigoCentroCosto != "") {
            $dql .= " AND e.codigoCentroCostoFk = " . $strCodigoCentroCosto;
        }      
        if($boolMostrarActivos == 1 ) {
            $dql .= " AND e.estadoActivo = 1";
        }
        $dql .= " ORDER BY e.nombreCorto";
        return $dql;
    }                    
}