<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoCentroCostoRepository extends EntityRepository {

    public function listaDql($anio = "", $mes = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ecc FROM BrasaRecursoHumanoBundle:RhuEmpleadoCentroCosto ecc WHERE ecc.codigoEmpleadoCentroCostoPk <> 0";               
        if($anio != "") {
             $dql .= " AND ecc.anio = " . $anio;
        }
        if($mes != "") {
             $dql .= " AND ecc.mes = " . $mes;
        }        
        $dql .= " ORDER BY ecc.anio, ecc.mes DESC";
        return $dql;
    }
    
}