<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuExamenRestriccionMedicaDetalleRepository extends EntityRepository {
    
    public function tiposRestriccionesMedicas($CodigoExamenRestriccionMedica) {
        $em = $this->getEntityManager();
        $db = $em->getConnection();
        $query = "SELECT codigo_examen_restriccion_medica_tipo_pk as codigoExamenRestriccionMedicaTipoPk, nombre "         
        . " FROM rhu_examen_restriccion_medica_tipo "
        . "WHERE rhu_examen_restriccion_medica_tipo.codigo_examen_restriccion_medica_tipo_pk NOT IN (SELECT rhu_examen_restriccion_medica_detalle.codigo_examen_restriccion_medica_tipo_fk FROM rhu_examen_restriccion_medica_detalle)";
        $stmt = $db->prepare($query);
        $params = array();
        $stmt->execute($params);
        $arExamenRestriccionMedicaTipos=$stmt->fetchAll();
        return $arExamenRestriccionMedicaTipos;
    }
    
}