<?php

namespace Brasa\RecursoHumanoBundle\Repository;

/**
 * RhuEmpleadoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
