<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuExamenTipoRepository extends EntityRepository {
    
    public function ordenarExamenTipos() {
        $em = $this->getEntityManager();
        $dql   = "SELECT s FROM BrasaRecursoHumanoBundle:RhuExamenTipo s order by s.nombre";
        $query = $em->createQuery($dql);
        return $query;
    }
    
}