<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuHorarioAccesoRepository extends EntityRepository {
    
    public function RegistroHoy($strFechaHoy = "") {
        
        $em = $this->getEntityManager();
        $dql   = "SELECT ha FROM BrasaRecursoHumanoBundle:RhuHorarioAcceso ha WHERE ha.codigoHorarioAccesoPk <> 0 ";   
        if ($strFechaHoy != ""){
            $dql .= " AND ha.fecha LIKE '%". date_format($strFechaHoy, ('Y-m-d')). "%'";
        }
        return $dql;
    }
    
    public function listaDql($strIdentificacion = "", $strNombre = "", $strDesde = "", $strHasta = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ha,e FROM BrasaRecursoHumanoBundle:RhuHorarioAcceso ha JOIN ha.empleadoRel e WHERE ha.codigoHorarioAccesoPk <> 0 ";   
        if($strIdentificacion != "") {
            $dql .= " AND e.numeroIdentificacion = " . $strIdentificacion;
        }   
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%". $strNombre . "%'";
        }
        if ($strDesde != ""){
            $dql .= " AND ha.fecha >='" . date_format($strHasta, ('Y-m-d')) . "'";
        }
        if($strHasta != "") {
            $dql .= " AND ha.fecha <='" . date_format($strHasta, ('Y-m-d')) . "'";
        }
        //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
        return $dql;
    }
    
}