<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuIbcRepository extends EntityRepository {
    
    public function devuelveIbcFecha($codigoEmpleado, $fechaDesde, $fechaHasta, $codigoContrato) {
            $em = $this->getEntityManager();
            $dql   = "SELECT SUM(ibc.vrIngresoBaseCotizacion) FROM BrasaRecursoHumanoBundle:RhuIbc ibc "
                    . "WHERE ibc.codigoEmpleadoFk = " . $codigoEmpleado . " "
                    . "AND ibc.codigoContratoFk = " . $codigoContrato . " "
                    . "AND ibc.fechaDesde >= '" . $fechaDesde . "' AND ibc.fechaHasta <= '" . $fechaHasta . "'";
            $query = $em->createQuery($dql);
            $arrayResultado = $query->getResult();
            return $arrayResultado;
        }    
    
}