<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuLicenciaRepository extends EntityRepository {
    
    public function pendientesCentroCosto($strCodigoCentroCosto) {
        $em = $this->getEntityManager();                
        $dql   = "SELECT l FROM BrasaRecursoHumanoBundle:RhuLicencia l "
                . "WHERE l.codigoCentroCostoFk = " . $strCodigoCentroCosto . " "
                . "AND l.cantidadPendiente != 0 ";
        $query = $em->createQuery($dql);
        $arLicenciasPendientes = $query->getResult();
        return $arLicenciasPendientes;        
    }
        
    public function pendientesEmpleado($strCodigoEmpleado) {
        $em = $this->getEntityManager();                
        $dql   = "SELECT l FROM BrasaRecursoHumanoBundle:RhuLicencia l "
                . "WHERE l.codigoEmpleadoFk = " . $strCodigoEmpleado . " "
                . "AND l.cantidadPendiente != 0 ";
        $query = $em->createQuery($dql);
        $arLicenciasPendientesEmpleado = $query->getResult();
        return $arLicenciasPendientesEmpleado;        
    }
    
    public function diasLicencia($fechaDesde, $fechaHasta, $codigoEmpleado) {
        $em = $this->getEntityManager();
        $dql = "SELECT licencia FROM BrasaRecursoHumanoBundle:RhuLicencia licencia "
                . "WHERE (licencia.fechaDesde >= '" . $fechaDesde . "' OR licencia.fechaHasta = '0000-00-00') "
                . "AND licencia.fechaDesde <='" . $fechaHasta . "' "
                . "AND licencia.codigoEmpleadoFk = '" . $codigoEmpleado . "'";       
        $objQuery = $em->createQuery($dql);  
        $arLicencias = $objQuery->getResult();                
        $intDiasLicencia = 0;
        foreach ($arLicencias as $arLicencias) {
            $dateFechaDesde =  "";
            $dateFechaHasta =  "";               
            if($arIncapacidad->getFechater() > $fechaHasta == true) {
                $dateFechaHasta = $fechaHasta;
            } else {
                $dateFechaHasta = $arIncapacidad->getFechater();
            }

            if($arIncapacidad->getFechaini() <  $fechaDesde == true) {
                $dateFechaDesde = $fechaDesde;
            } else {
                $dateFechaDesde = $arIncapacidad->getFechaini();
            }

            if($dateFechaDesde != "" && $dateFechaHasta != "") {
                $intDias = $dateFechaDesde->diff($dateFechaHasta);
                $intDias = $intDias->format('%a');
                $intDiasIncapacidad += $intDias + 1;
            }  
        }
        if($intDiasIncapacidad > 30) {
            $intDiasIncapacidad = 30;
        }
         * 
         */
        return 0;
    }                
}