<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuLicenciaRepository extends EntityRepository {
    
    public function pendientesCentroCosto($strCodigoCentroCosto) {
        $em = $this->getEntityManager();                
        $dql   = "SELECT l FROM BrasaRecursoHumanoBundle:RhuLicencia l "
                . "WHERE l.codigoCentroCostoFk = " . $strCodigoCentroCosto . " "
                . "AND l.cantidadPendiente != 0 ";
        $query = $em->createQuery($dql);
        $arLicenciasPendientes = $query->getResult();
        return $arLicenciasPendientes;        
    }
        
    public function pendientesEmpleado($strCodigoEmpleado) {
        $em = $this->getEntityManager();                
        $dql   = "SELECT l FROM BrasaRecursoHumanoBundle:RhuLicencia l "
                . "WHERE l.codigoEmpleadoFk = " . $strCodigoEmpleado . " "
                . "AND l.cantidadPendiente != 0 ";
        $query = $em->createQuery($dql);
        $arLicenciasPendientesEmpleado = $query->getResult();
        return $arLicenciasPendientesEmpleado;        
    }
    
    public function diasLicencia($fechaDesde, $fechaHasta, $codigoEmpleado, $tipo) {
        $em = $this->getEntityManager();
        $dql = "SELECT licencia FROM BrasaRecursoHumanoBundle:RhuLicencia licencia "
                . "WHERE (licencia.fechaDesde >= '" . $fechaDesde->format('Y-m-d') . "' OR licencia.fechaHasta = '0000-00-00') "
                . "AND licencia.fechaDesde <='" . $fechaHasta->format('Y-m-d') . "' "
                . "AND licencia.codigoEmpleadoFk = '" . $codigoEmpleado . "' ";

        if($tipo == 1) {
            $dql = $dql . "AND (licencia.codigoPagoAdicionalSubtipoFk = 48 OR licencia.codigoPagoAdicionalSubtipoFk = 43)";       
        } else {
            $dql = $dql . "AND licencia.codigoPagoAdicionalSubtipoFk <> 48 AND licencia.codigoPagoAdicionalSubtipoFk <> 43";       
        }
        $objQuery = $em->createQuery($dql);  
        $arLicencias = $objQuery->getResult();                
        $intDiasLicencia = 0;
        foreach ($arLicencias as $arLicencia) {
            $dateFechaDesde =  "";
            $dateFechaHasta =  "";               
            if($arLicencia->getFechaHasta() > $fechaHasta == true) {
                $dateFechaHasta = $fechaHasta;
            } else {
                $dateFechaHasta = $arLicencia->getFechaHasta();
            }

            if($arLicencia->getFechaDesde() <  $fechaDesde == true) {
                $dateFechaDesde = $fechaDesde;
            } else {
                $dateFechaDesde = $arLicencia->getFechaDesde();
            }

            if($dateFechaDesde != "" && $dateFechaHasta != "") {
                $intDias = $dateFechaDesde->diff($dateFechaHasta);
                $intDias = $intDias->format('%a');
                $intDiasLicencia += $intDias + 1;
            }  
        }
        if($intDiasLicencia > 30) {
            $intDiasLicencia = 30;
        }
        return $intDiasLicencia;
    }                
}