<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuLiquidacionRepository extends EntityRepository {
    
    public function listaDQL($strIdentificacion = "") {        
        $dql   = "SELECT l, e FROM BrasaRecursoHumanoBundle:RhuLiquidacion l JOIN l.empleadoRel e WHERE l.codigoLiquidacionPk <> 0";
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }

        $dql .= " ORDER BY l.codigoLiquidacionPk";
        return $dql;
    }  
    
    public function liquidar($codigoLiquidacion) {        
        $em = $this->getEntityManager();
        $arLiquidacion = new \Brasa\RecursoHumanoBundle\Entity\RhuLiquidacion();
        $arLiquidacion = $em->getRepository('BrasaRecursoHumanoBundle:RhuLiquidacion')->find($codigoLiquidacion); 
        $douIBCAdicional = 0;
        $dateFechaUltimoPago = $em->getRepository('BrasaRecursoHumanoBundle:RhuPago')->devuelveFechaUltimoPago($arLiquidacion->getCodigoEmpleadoFk());                        
        if($dateFechaUltimoPago != null) {
            $arLiquidacion->setFechaUltimoPago(date_create($dateFechaUltimoPago));
            if($arLiquidacion->getFechaUltimoPago() < $arLiquidacion->getFechaHasta()) {
                $diasAdicionales = $arLiquidacion->getFechaUltimoPago()->diff($arLiquidacion->getFechaHasta());
                $diasAdicionales = $diasAdicionales->format('%a');
                $douIBCAdicional = ($arLiquidacion->getContratoRel()->getVrSalario()/30) * $diasAdicionales;
                $arLiquidacion->setVrIngresoBaseCotizacionAdicional($douIBCAdicional);                
                $arLiquidacion->setDiasAdicionalesIBC($diasAdicionales);
            }
        }        
        $douIBC = $em->getRepository('BrasaRecursoHumanoBundle:RhuPago')->devuelveCostosFecha($arLiquidacion->getCodigoEmpleadoFk(), $arLiquidacion->getContratoRel()->getFechaDesde()->format('Y-m-d'), $arLiquidacion->getContratoRel()->getFechaHasta()->format('Y-m-d'));        
        $douIBCTotal = $douIBC + $douIBCAdicional;
        $intDiasLaborados = $arLiquidacion->getContratoRel()->getFechaDesde()->diff($arLiquidacion->getContratoRel()->getFechaHasta());
        $intDiasLaborados = $intDiasLaborados->format('%a');
        $douSalario = $arLiquidacion->getContratoRel()->getVrSalario();
        $douBasePrestacionesTotal = 0;        
        $douCesantias = 0;
        $douInteresesCesantias = 0;
        $douPrima = 0;
        $douVacaciones = 0;
        if($intDiasLaborados > 0) {
            $douBasePrestaciones = ($douIBCTotal / $intDiasLaborados) * 30;            
            //$douAuxilioTransporte = 74000; // Traer de la base de datos
            $arConfiguracion = $em->getRepository('BrasaRecursoHumanoBundle:RhuConfiguracion')->configuracionDatoCodigo(1);//AUXILIO TRANSPORTE
            $douAuxilioTransporte = $arConfiguracion->getVrAuxilioTransporte();
            $douBasePrestacionesTotal = $douBasePrestaciones + $douAuxilioTransporte;
            $arLiquidacion->setVrBasePrestaciones($douBasePrestaciones);
            $arLiquidacion->setVrAuxilioTransporte($douAuxilioTransporte);
            $arLiquidacion->setVrBasePrestacionesTotal($douBasePrestacionesTotal);            
        }  

        if($arLiquidacion->getLiquidarCesantias() == 1) {
            if($arLiquidacion->getContratoRel()->getFechaUltimoPagoCesantias() <= $arLiquidacion->getContratoRel()->getFechaDesde()) {
                $intDiasCesantias = $arLiquidacion->getContratoRel()->getFechaUltimoPagoCesantias()->diff($arLiquidacion->getContratoRel()->getFechaHasta());
                $intDiasCesantias = $intDiasCesantias->format('%a');                
                $douCesantias = ($douBasePrestacionesTotal * $intDiasCesantias) / 360;
                $douInteresesCesantias = ($douCesantias * 0.12 * $intDiasCesantias) / 360;
                $arLiquidacion->setDiasCesantias($intDiasCesantias);
                $arLiquidacion->setVrCesantias($douCesantias);
                $arLiquidacion->setVrInteresesCesantias($douInteresesCesantias);
            }            
        }
        if($arLiquidacion->getLiquidarPrima() == 1) {
            if($arLiquidacion->getContratoRel()->getFechaUltimoPagoPrimas() <= $arLiquidacion->getContratoRel()->getFechaDesde()) {
                $intDiasPrima = $arLiquidacion->getContratoRel()->getFechaUltimoPagoPrimas()->diff($arLiquidacion->getContratoRel()->getFechaHasta());
                $intDiasPrima = $intDiasPrima->format('%a');
                $douPrima = ($douBasePrestacionesTotal * $intDiasPrima) / 360;                
                $arLiquidacion->setDiasPrimas($intDiasPrima);
                $arLiquidacion->setVrPrima($douPrima);                
            }            
        }

        if($arLiquidacion->getContratoRel()->getFechaUltimoPagoVacaciones() <= $arLiquidacion->getContratoRel()->getFechaDesde()) {
            if($arLiquidacion->getLiquidarVacaciones() == 1) {
                $intDiasVacaciones = $arLiquidacion->getContratoRel()->getFechaDesde()->diff($arLiquidacion->getContratoRel()->getFechaHasta());
                $intDiasVacaciones = $intDiasVacaciones->format('%a');                
                $douVacaciones = ($douSalario * $intDiasVacaciones) / 720;
                $arLiquidacion->setDiasVacaciones($intDiasVacaciones);
                $arLiquidacion->setVrVacaciones($douVacaciones);
            }
        }       
        $douTotal = $douCesantias + $douInteresesCesantias + $douPrima + $douVacaciones;
        $arLiquidacion->setVrTotal($douTotal);
        $arLiquidacion->setVrSalario($douSalario);
        $arLiquidacion->setVrIngresoBaseCotizacion($douIBC);
        $arLiquidacion->setVrIngresoBaseCotizacionTotal($douIBCTotal); 
        $intDiasTotal = $arLiquidacion->getContratoRel()->getFechaDesde()->diff($arLiquidacion->getContratoRel()->getFechaHasta());
        $intDiasTotal = $intDiasTotal->format('%a');
        $arLiquidacion->setNumeroDias($intDiasTotal);
        $em->flush();
        return true;
    } 
    
    public function devuelveCesantiasFecha($codigoEmpleado, $fechaDesde, $fechaHasta) {
        $em = $this->getEntityManager();
        $dql   = "SELECT SUM(l.VrCesantias) as Cesantias FROM BrasaRecursoHumanoBundle:RhuLiquidacion l "
                . "WHERE l.codigoEmpleadoFk = " . $codigoEmpleado 
                . "AND l.fechaDesde >= '" . $fechaDesde . "' AND l.fechaDesde <= '" . $fechaHasta . "'";
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        return $arrayResultado;
    } 
}