<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPagoDetalleRepository extends EntityRepository {
    /*public function pagosDetallesProgramacionPago($codigoProgramacionPago) {
        $em = $this->getEntityManager();
        $dql   = "SELECT pd FROM BrasaRecursoHumanoBundle:RhuPagoDetalle pd JOIN pd.pagoRel p "
                . "WHERE p.codigoProgramacionPagoFk = " . $codigoProgramacionPago;
        $query = $em->createQuery($dql);
        $arPagosDetalles = $query->getResult();                
        return $arPagosDetalles;
    }*/
    public function certificadoingresosTotalPagosEmpleado($codigoEmpleado, $strFechaCertificado) {
        $em = $this->getEntityManager();
        $dql   = "SELECT pd FROM BrasaRecursoHumanoBundle:RhuPagoDetalle pd JOIN pd.pagoRel p "
                . "WHERE p.codigoEmpleadoFk = " . $codigoEmpleado . " "
                . "AND pd.codigoPagoConceptoFk = 1"
                . "AND p.fechaDesde like '%" . $strFechaCertificado . "%' ";
        $query = $em->createQuery($dql);
        $douIBC = $query->getResult();
        return $douIBC;
    }
    public function certificadoingresosTotalPagosEmpleadoAuxilio($codigoEmpleado, $strFechaCertificado) {
        $em = $this->getEntityManager();
        $dql   = "SELECT pd FROM BrasaRecursoHumanoBundle:RhuPagoDetalle pd JOIN pd.pagoRel p "
                . "WHERE p.codigoEmpleadoFk = " . $codigoEmpleado . " "
                . "AND pd.codigoPagoConceptoFk = 18"
                . "AND p.fechaDesde like '%" . $strFechaCertificado . "%' ";
        $query = $em->createQuery($dql);
        $douAuxilio = $query->getResult();
        return $douAuxilio;
    }
}