<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuProgramacionPagoDetalleRepository extends EntityRepository {
    public function listaDQL($codigoProgramacionPago = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT pd FROM BrasaRecursoHumanoBundle:RhuProgramacionPagoDetalle pd WHERE pd.codigoProgramacionPagoDetallePk <> 0" ;
        if($codigoProgramacionPago != "" ) {
            $dql .= " AND pd.codigoProgramacionPagoFk = " . $codigoProgramacionPago;
        }             

        return $dql;
    }                        
}