<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPermisoRepository extends EntityRepository {
    
    public function listaDQL($strIdentificacion = "", $codigoCentroCosto = "", $strDesde = "", $strHasta = "") {        
        $dql   = "SELECT p, e FROM BrasaRecursoHumanoBundle:RhuPermiso p JOIN p.empleadoRel e WHERE p.codigoPermisoPk <> 0";
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        if($codigoCentroCosto != "" || $codigoCentroCosto != 0 ) {
            $dql .= " AND e.codigoCentroCostoFk = " . $codigoCentroCosto;
        }
        if ($strDesde != ""){
            $dql .= " AND p.fechaPermiso >='" . $strDesde . "'";
        }
        if($strHasta != "") {
            $dql .= " AND p.fechaPermiso <='" . $strHasta . "'";
        }
        $dql .= " ORDER BY p.fechaPermiso";
        return $dql;
    }
    
    public function permisosAutorizados($strNombre = "", $strIdentificacion = "", $codigoCentroCosto = "", $codigoCargo = "", $codigoDepartametoEmpresa = "", $afectaHorario, $strDesde = "", $strHasta = "") {        
        $dql   = "SELECT p, e FROM BrasaRecursoHumanoBundle:RhuPermiso p JOIN p.empleadoRel e WHERE p.codigoPermisoPk <> 0 AND p.estadoAutorizado = 1";
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        if($codigoCentroCosto != "" || $codigoCentroCosto != 0 ) {
            $dql .= " AND e.codigoCentroCostoFk = " . $codigoCentroCosto;
        }
        if($codigoCargo != "" || $codigoCargo != 0 ) {
            $dql .= " AND e.codigoCargoFk = " . $codigoCargo;
        }
        if($codigoDepartametoEmpresa != "" || $codigoDepartametoEmpresa != 0 ) {
            $dql .= " AND e.codigoDepartamentoEmpresaFk = " . $codigoDepartametoEmpresa;
        }
        if($afectaHorario == 1 ) {
            $dql .= " AND p.afectaHorario = 1";
        }
        if($afectaHorario == 0 ) {
            $dql .= " AND p.afectaHorario = 0";
        }
        if ($strDesde != ""){
            $dql .= " AND p.fechaPermiso >='" . $strDesde . "'";
        }
        if($strHasta != "") {
            $dql .= " AND p.fechaPermiso <='" . $strHasta . "'";
        }
        $dql .= " ORDER BY p.fechaPermiso";
        return $dql;
    }
    
    public function horasPermisoPeriodo($fechaDesde = '', $fechaHasta = '', $codigoEmpleado) {
        $em = $this->getEntityManager();
        $horas = 0;
        $dql   = "SELECT SUM(p.horasPermiso) as horas "
                . "FROM BrasaRecursoHumanoBundle:RhuPermiso p "
                . "WHERE p.fechaPermiso >='" . $fechaDesde . "' AND p.fechaPermiso <= '" . $fechaHasta . "' AND p.codigoEmpleadoFk = " . $codigoEmpleado . " AND p.afectaHorario = 0 AND p.estadoAutorizado = 1";
        $query = $em->createQuery($dql);
        $arResultado = $query->getResult();
        if($arResultado[0]['horas'] != null) {
          $horas = $arResultado[0]['horas'];
        }
        return $horas;
    } 
    
    public function permisoPeriodo($fechaDesde = '', $fechaHasta = '', $codigoEmpleado) {
        $em = $this->getEntityManager();
        $dql   = "SELECT p FROM BrasaRecursoHumanoBundle:RhuPermiso p "
                . "WHERE p.fechaPermiso >='" . $fechaDesde . "' AND p.fechaPermiso <= '" . $fechaHasta . "' AND p.codigoEmpleadoFk = " . $codigoEmpleado . " ";
        $query = $em->createQuery($dql);
        $arResultado = $query->getResult();
        return $arResultado;
    }    
    
}