<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPermisoRepository extends EntityRepository {
    
    public function listaDQL($strIdentificacion = "", $codigoCentroCosto = "", $strDesde = "", $strHasta = "") {        
        $dql   = "SELECT p, e FROM BrasaRecursoHumanoBundle:RhuPermiso p JOIN p.empleadoRel e WHERE p.codigoPermisoPk <> 0";
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        if($codigoCentroCosto != "" || $codigoCentroCosto != 0 ) {
            $dql .= " AND e.codigoCentroCostoFk = " . $codigoCentroCosto;
        }
        if ($strDesde != ""){
            $dql .= " AND p.fechaPermiso >='" . date_format($strDesde, ('Y-m-d')) . "'";
        }
        if($strHasta != "") {
            $dql .= " AND p.fechaPermiso <='" . date_format($strHasta, ('Y-m-d')) . "'";
        }
        $dql .= " ORDER BY p.fechaPermiso";
        return $dql;
    }
}