<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPagoBancoDetalleRepository extends EntityRepository {                
    public function pendientesContabilizarDql() {        
        $dql   = "SELECT pbd FROM BrasaRecursoHumanoBundle:RhuPagoBancoDetalle pbd WHERE pbd.estadoContabilizado = 0";       
        $dql .= " ORDER BY pbd.codigoPagoBancoDetallePk DESC";
        return $dql;
    }                                
}