<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuHorarioAccesoRepository extends EntityRepository {
    
    /*public function RegistroHoy($strFechaHoy = "") {
        
        $em = $this->getEntityManager();
        $dql   = "SELECT ha FROM BrasaRecursoHumanoBundle:RhuHorarioAcceso ha WHERE ha.codigoHorarioAccesoPk <> 0 ";   
        if ($strFechaHoy != ""){
            $dql .= " AND ha.fecha >= '". $strFechaHoy . " 00:00:00' AND ha.fecha <= '" . $strFechaHoy . " 23:59:59' ";
        }
        return $dql;
    }
    
    public function listaDql($strIdentificacion = "", $strNombre = "", $strDesde = "", $strHasta = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ha,e FROM BrasaRecursoHumanoBundle:RhuHorarioAcceso ha JOIN ha.empleadoRel e WHERE ha.codigoHorarioAccesoPk <> 0 ";   
        if($strIdentificacion != "") {
            $dql .= " AND e.numeroIdentificacion = " . $strIdentificacion;
        }   
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%". $strNombre . "%'";
        }
        if ($strDesde != ""){
            $dql .= " AND ha.fecha >= '". date_format($strDesde, 'Y-m-d') . " 00:00:00'";
        }
        if($strHasta != "") {
            $dql .= " AND ha.fecha <= '". date_format($strHasta, 'Y-m-d') . " 23:59:59'";
        }
        $dql .= " ORDER BY ha.fecha";
        return $dql;
    }*/
    
}