<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuRequisitoRepository extends EntityRepository {
    public function listaDQL() {        
        $dql   = "SELECT r FROM BrasaRecursoHumanoBundle:RhuRequisito r WHERE r.codigoRequisitoPk <> 0";
        return $dql;
    }                                
}