<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuRegistroVisitaRepository extends EntityRepository {
    
    public function RegistroHoy($strFechaHoy = "") {
        
        $em = $this->getEntityManager();
        $dql   = "SELECT rv FROM BrasaRecursoHumanoBundle:RhuRegistroVisita rv WHERE rv.codigoRegistroVisitaPk <> 0 AND rv.estado = 0 ";   
        if ($strFechaHoy != ""){
            $dql .= " AND rv.fechaEntrada >= '". $strFechaHoy . " 00:00:00' AND rv.fechaEntrada <= '" . $strFechaHoy . " 23:59:59' ";
        }
        return $dql;
    }
    public function RegistroEntrada($strFechaHoy = "", $strIdentificacion= "") {
        
        $em = $this->getEntityManager();
        $dql   = "SELECT rv FROM BrasaRecursoHumanoBundle:RhuRegistroVisita rv WHERE rv.codigoRegistroVisitaPk <> 0 AND rv.estado = 0 ";   
        if ($strFechaHoy != ""){
            $dql .= " AND rv.fechaEntrada >= '". $strFechaHoy . " 00:00:00' AND rv.fechaEntrada <= '" . $strFechaHoy . " 23:59:59' ";
        }
        if ($strIdentificacion != ""){
            $dql .= " AND rv.numeroIdentificacion = ". $strIdentificacion;
        }
        $query = $em->createQuery($dql);
        $arVisitaEntrada = $query->getResult();
        return $arVisitaEntrada;
    }
    
    public function listaDql($strIdentificacion = "", $strNombre = "", $strDesde = "", $strHasta = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT rv FROM BrasaRecursoHumanoBundle:RhuRegistroVisita rv WHERE rv.codigoRegistroVisitaPk <> 0 ";   
        if($strIdentificacion != "") {
            $dql .= " AND rv.numeroIdentificacion = " . $strIdentificacion;
        }   
        if($strNombre != "" ) {
            $dql .= " AND rv.nombre LIKE '%". $strNombre . "%'";
        }
        if ($strDesde != ""){
            $dql .= " AND rv.fechaEntrada >= '". $strDesde . " 00:00:00'";
        }
        if($strHasta != "") {
            $dql .= " AND rv.fechaEntrada <= '". $strHasta . " 23:59:59'";
        }
        $dql .= " ORDER BY rv.fechaEntrada";
        return $dql;
    }
    
}