<?php

namespace Brasa\RecursoHumanoBundle\Repository;

/**
 * RhuSubzonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSubzonaRepository extends \Doctrine\ORM\EntityRepository
{
}
