<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSSPeriodoRepository extends EntityRepository {
    
    public function listaDQL() {        
            $em = $this->getEntityManager();
            $dql   = "SELECT p FROM BrasaRecursoHumanoBundle:RhuSSPeriodo p WHERE p.codigoPeriodoPk <> 0";
            return $dql;
        } 
    
    public function generar($codigoPeriodo) {
        $em = $this->getEntityManager();
        $arSSPeriodo = new \Brasa\RecursoHumanoBundle\Entity\RhuSSPeriodo();
        $arSSPeriodo = $em->getRepository('BrasaRecursoHumanoBundle:RhuSSPeriodo')->find($codigoPeriodo);
        //$intDiaFinal = date("d",(mktime(0,0,0,$arSSPeriodo->getMes() +1,1,$arSSPeriodo->getAnio())-1));        
        $arContratos = $em->getRepository('BrasaRecursoHumanoBundle:RhuContrato')->contratosInicioFecha($arSSPeriodo->getFechaDesde()->format('Y-m-d'), $arSSPeriodo->getFechaHasta()->format('Y-m-d'));
        foreach ($arContratos AS $arContrato) {
            $arSSPeriodoDetalle = new \Brasa\RecursoHumanoBundle\Entity\RhuSSPeriodoDetalle();
            $arSSPeriodoDetalle->setSsPeriodoRel($arSSPeriodo);
            $arSSPeriodoDetalle->setContratoRel($arContrato);
            $arSSPeriodoDetalle->setEmpleadoRel($arContrato->getEmpleadoRel()); 
            $arSSPeriodoDetalle->setTipoRegistro('02');
            $arSSPeriodoDetalle->setSecuencia('00000');
            $arSSPeriodoDetalle->setTipoDocumentoCotizante($arContrato->getEmpleadoRel()->getTipoIdentificacionRel()->getNombre());
            $em->persist($arSSPeriodoDetalle);
        }
        $em->flush();
        return true;
    }
}