<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSsoAporteRepository extends EntityRepository {
    public function listaDQL($codigoPeriodoDetalle) {                    
            $dql   = "SELECT a FROM BrasaRecursoHumanoBundle:RhuSsoAporte a WHERE a.codigoPeriodoDetalleFk = " . $codigoPeriodoDetalle;
            return $dql;
        }     
}