<?php

namespace Brasa\RecursoHumanoBundle\Repository;

/**
 * RhuSalarioTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSalarioTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
