<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSsoAporteRepository extends EntityRepository {
    
    public function listaDQL($codigoPeriodoDetalle, $strCodigoCentroCosto) {                    
            $dql   = "SELECT a, e FROM BrasaRecursoHumanoBundle:RhuSsoAporte a JOIN a.empleadoRel e WHERE a.codigoPeriodoDetalleFk = " . $codigoPeriodoDetalle;
            if($strCodigoCentroCosto != "") {
                $dql .= " AND e.codigoCentroCostoFk = " . $strCodigoCentroCosto;
            }
            return $dql;
    }
    
    public function listaAportesDQL($anio = "", $mes ="", $strIdentificacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT ssoa, e FROM BrasaRecursoHumanoBundle:RhuSsoAporte ssoa JOIN ssoa.empleadoRel e WHERE ssoa.codigoAportePk <> 0 ";   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if ($anio != ""){
            $dql .= " AND ssoa.anio = " . $anio;
        }
        if($mes != "") {
            $dql .= " AND ssoa.mes = " . $mes;
        }
        return $dql;
    }
    
    public function devuelveCostosParafiscales($fechaDesde = "", $fechaHasta = "", $fechaProceso = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT a, ap, c FROM BrasaRecursoHumanoBundle:RhuSsoAporte a JOIN a.ssoPeriodoRel ap JOIN a.contratoRel c WHERE a.codigoAportePk <> 0"
                . "AND ap.fechaDesde >= '" . $fechaDesde . "' AND ap.fechaDesde <= '" . $fechaHasta . "'";
                if ($fechaProceso != ""){
                    $dql .= " AND ap.fechaDesde LIKE '%".$fechaProceso. "%' AND ap.fechaHasta LIKE '%".$fechaProceso. "%'";
                }
                
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        return $arrayResultado;
    }
    
    //Esta funcion se utiliza en la utilidad de supervigilancia - parafiscales         
    public function parafiscalesSupervigilancia($fechaDesde, $fechaHasta) {
        /*$em = $this->getEntityManager();
        $dql   = "SELECT a.mes, c.nombre, COUNT(a.codigoAportePk) as numeroEmpleados, SUM(a.cotizacionSalud) as eps, SUM(a.cotizacionPension) as pension, SUM(a.cotizacionRiesgos) as arl, SUM(a.cotizacionCaja) as ccf, SUM(a.cotizacionSena) as sena, SUM(a.cotizacionIcbf) as icbf, SUM(a.ibcPension) as nomina FROM BrasaRecursoHumanoBundle:RhuSsoAporte a JOIN a.empleadoRel e JOIN a.cargoRel c "
                . "WHERE a.fechaDesde >= '" . $fechaDesde . "' AND a.fechaHasta <= '" . $fechaHasta . "' "
                . "GROUP BY a.mes, a.codigoCargoFk";
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        return $arrayResultado;*/
        $em = $this->getEntityManager();
        $dql   = "SELECT a.mes, cs.nombre, COUNT(a.codigoAportePk) as numeroEmpleados, SUM(a.cotizacionSalud) as eps, SUM(a.cotizacionPension) as pension, SUM(a.cotizacionRiesgos) as arl, SUM(a.cotizacionCaja) as ccf, SUM(a.cotizacionSena) as sena, SUM(a.cotizacionIcbf) as icbf, SUM(a.ibcPension) as nomina FROM BrasaRecursoHumanoBundle:RhuSsoAporte a JOIN a.empleadoRel e JOIN a.cargoRel c LEFT JOIN c.cargoSupervigilanciaRel cs "
                . "WHERE a.fechaDesde >= '" . $fechaDesde . "' AND a.fechaHasta <= '" . $fechaHasta . "' "
                . "GROUP BY a.mes, cs.nombre";
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        return $arrayResultado;
    } 
    
    public function cotizacionMes($anio, $mes, $codigoContrato) {
        $em = $this->getEntityManager();
        $dql   = "SELECT SUM(ssoa.cotizacionPension) as cotizacionPension, SUM(ssoa.cotizacionSalud) as cotizacionSalud, SUM(ssoa.cotizacionRiesgos) as cotizacionRiesgos, SUM(ssoa.cotizacionCaja) as cotizacionCaja, SUM(ssoa.cotizacionSena) as cotizacionSena, SUM(ssoa.cotizacionIcbf) as cotizacionIcbf FROM BrasaRecursoHumanoBundle:RhuSsoAporte ssoa "
                . "WHERE ssoa.anio = $anio AND ssoa.mes = $mes" . " "
                . "AND ssoa.codigoContratoFk = " . $codigoContrato;
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        $resultados = $arrayResultado[0];
        if($resultados['cotizacionRiesgos'] == null) {
           $resultados['cotizacionRiesgos'] = 0; 
        }
        if($resultados['cotizacionCaja'] == null) {
           $resultados['cotizacionCaja'] = 0; 
        }        
        if($resultados['cotizacionSena'] == null) {
           $resultados['cotizacionSena'] = 0; 
        }
        if($resultados['cotizacionIcbf'] == null) {
           $resultados['cotizacionIcbf'] = 0; 
        }        
        if($resultados['cotizacionPension'] == null) {
           $resultados['cotizacionPension'] = 0; 
        } 
        if($resultados['cotizacionSalud'] == null) {
           $resultados['cotizacionSalud'] = 0; 
        }         
        return $resultados;        
    }
}