<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSoportePagoHorarioDetalleRepository extends EntityRepository {
    
    public function listaDql($codigoSoportePagoHorario) {
        $dql   = "SELECT sphd FROM BrasaRecursoHumanoBundle:RhuSoportePagoHorarioDetalle sphd WHERE sphd.codigoSoportePagoHorarioFk = " . $codigoSoportePagoHorario;
        return $dql;
    }
    
    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if(count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {
                $ar = $em->getRepository('BrasaRecursoHumanoBundle:RhuSoportePagoHorarioDetalle')->find($codigo);
                $em->remove($ar);
            }
            $em->flush();
        }
    }        
}