<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuVacacionAdicionalRepository extends EntityRepository {    
    public function listaDql($codigoVacacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT va FROM BrasaRecursoHumanoBundle:RhuVacacionAdicional va WHERE va.codigoVacacionAdicionalPk <> 0";

        if($codigoVacacion != "") {
            $dql .= " AND va.codigoVacacionFk = " . $codigoVacacion;
        }        
        $dql .= " ORDER BY va.codigoVacacionAdicionalPk";
        return $dql;
    }     
    public function listaConsultaDql($fechaDesde = "", $fechaHasta = "", $codigoEmpleado = "", $codigoPagoConcepto = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT va FROM BrasaRecursoHumanoBundle:RhuVacacionAdicional va JOIN va.vacacionRel v WHERE va.codigoVacacionAdicionalPk <> 0";        
        $dql .= " AND v.fecha >= '" . $fechaDesde . "' AND v.fecha <='" . $fechaHasta . " '"; 
        if($codigoEmpleado != "") {
            $dql .= " AND v.codigoEmpleadoFk = " . $codigoEmpleado;
        }
        if($codigoPagoConcepto != "") {
            $dql .= " AND va.codigoPagoConceptoFk = " . $codigoPagoConcepto;
        }        
        return $dql;
    }    
}