<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuVacacionBonificacionRepository extends EntityRepository {    
    public function listaDql($codigoVacacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT vb FROM BrasaRecursoHumanoBundle:RhuVacacionBonificacion vb WHERE vb.codigoVacacionBonificacionPk <> 0";

        if($codigoVacacion != "") {
            $dql .= " AND vb.codigoVacacionFk = " . $codigoVacacion;
        }        
        $dql .= " ORDER BY vb.codigoVacacionBonificacionPk";
        return $dql;
    }                                
}