<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuVacacionAdicionalRepository extends EntityRepository {    
    public function listaDql($codigoVacacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT va FROM BrasaRecursoHumanoBundle:RhuVacacionAdicional va WHERE va.codigoVacacionAdicionalPk <> 0";

        if($codigoVacacion != "") {
            $dql .= " AND va.codigoVacacionFk = " . $codigoVacacion;
        }        
        $dql .= " ORDER BY va.codigoVacacionAdicionalPk";
        return $dql;
    }     
}