<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuVisitanteRepository extends EntityRepository {
    
    public function ListaDql($strNombre = "", $strIdentificacion = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT v FROM BrasaRecursoHumanoBundle:RhuVisitante v WHERE v.codigoVisitantePk <> 0";
        if($strNombre != "" ) {
            $dql .= " AND v.nombre LIKE '%" . $strNombre . "%'";
        }
        if($strIdentificacion != "" ) {
            $dql .= " AND v.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        $dql .= " ORDER BY v.nombre";
        return $dql;
    }
}