<?php

namespace Brasa\LogisticaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogGuiasRepository extends EntityRepository {
    public function GuiasDespachoDetalle($codigoDespacho) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT guias FROM BrasaLogisticaBundle:LogGuias guias WHERE guias.codigoDespachoFk = " . $codigoDespacho;
        $query = $em->createQuery($dql);        
        return $query;
    }
}