<?php

namespace Brasa\AfiliacionBundle\Repository;

/**
 * AfiFacturaDetalleCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfiFacturaDetalleCursoRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListaDql($codigoFactura) {
        $em = $this->getEntityManager();
        $dql   = "SELECT fdc FROM BrasaAfiliacionBundle:AfiFacturaDetalleCurso fdc WHERE fdc.codigoFacturaDetalleCursoPk <> 0 AND fdc.codigoFacturaFk = " . $codigoFactura;
        $dql .= " ORDER BY fdc.codigoFacturaDetalleCursoPk";
        return $dql;
    }            
    
    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if(count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {
                $ar = $em->getRepository('BrasaAfiliacionBundle:AfiFacturaDetalleCurso')->find($codigo);
                $arCurso = $em->getRepository('BrasaAfiliacionBundle:AfiCurso')->find($ar->getCodigoCursoFk());
                $arCurso->setEstadoFacturado(0);
                $em->persist($arCurso);
                $em->remove($ar);
            }
            $em->flush();
        }
    }     
}
