<?php

namespace Brasa\AfiliacionBundle\Repository;

/**
 * AfiFacturaDetalleCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfiPagoCursoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaDql($codigoPagoCurso) {
        $em = $this->getEntityManager();
        $dql   = "SELECT pcd FROM BrasaAfiliacionBundle:AfiPagoCursoDetalle pcd WHERE pcd.codigoPagoCursoDetallePk <> 0 AND pcd.codigoPagoCursoFk = " . $codigoPagoCurso;
        $dql .= " ORDER BY pcd.codigoPagoCursoDetallePk";
        return $dql;
    }            
    
    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if(count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {
                $ar = $em->getRepository('BrasaAfiliacionBundle:AfiPagoCursoDetalle')->find($codigo);
                $arCurso = $em->getRepository('BrasaAfiliacionBundle:AfiCurso')->find($ar->getCodigoCursoFk());
                $arCurso->setEstadoPagado(0);
                $em->persist($arCurso);
                $em->remove($ar);
            }
            $em->flush();
        }
    }     
}
