<?php

namespace Brasa\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteDespachosRepository extends EntityRepository {
    public function Generar($codigoDespacho) {        
        $em = $this->getEntityManager();
        $arDespacho = new \Brasa\TransporteBundle\Entity\TteDespachos();
        $arDespacho = $em->getRepository('BrasaTransporteBundle:TteDespachos')->find($codigoDespacho);
        $arDespacho->setEstadoGenerado(1);
        $em->persist($arDespacho);
        $em->flush(); 
        return "";
    }    
}