<?php

namespace Brasa\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtePlanesRecogidasRepository extends EntityRepository {
    public function Pendientes() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT planesrecogidas FROM BrasaTransporteBundle:TtePlanesRecogidas planesrecogidas "
                . "WHERE planesrecogidas.codigoPlanRecogidaPk <> 0";       
        $query = $em->createQuery($dql);        
        return $query;
    }            
}