<?php

namespace Brasa\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteProgramacionRecogidaRepository extends EntityRepository {
    public function listaDql($codigoProgramacionRecogida) {
        $dql   = "SELECT pr FROM BrasaTransporteBundle:TteProgramacionRecogida pr WHERE pr.codigoProgramacionRecogidaPk <> 0";
        if($codigoProgramacionRecogida != "") {
            $dql = $dql . " AND pr.codigoProgramacionRecogidaPk = " . $codigoProgramacionRecogida;
        }
        return $dql;
    }       
    
    public function Pendientes() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT planesrecogidas FROM BrasaTransporteBundle:TtePlanRecogida planesrecogidas "
                . "WHERE planesrecogidas.estadoDescargado = 0";       
        $query = $em->createQuery($dql);        
        return $query;
    }            
}