<?php

namespace Brasa\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteRecibosCajaRepository extends EntityRepository {    
    public function RecibosCajaGuiasDetalle($codigoGuia) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT recibos FROM BrasaTransporteBundle:TteRecibosCaja recibos WHERE recibos.codigoGuiaFk = " . $codigoGuia;
        $query = $em->createQuery($dql);        
        return $query;
    }    
}