<?php

namespace Brasa\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteRecogidaRepository extends EntityRepository {                
    
    public function listaDql($codigoRecogida) {
        $dql   = "SELECT r FROM BrasaTransporteBundle:TteRecogida r WHERE r.codigoRecogidaPk <> 0";
        if($codigoRecogida != "") {
            $dql = $dql . " AND r.codigoRecogidaPk = " . $codigoRecogida;
        }
        return $dql;
    }       
    
    public function ListaPendientes() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT recogidas FROM BrasaTransporteBundle:TteRecogida recogidas "
                . "WHERE recogidas.estadoAsignada = 0";       
        $query = $em->createQuery($dql);        
        return $query;
    }            
    
    public function ListaAsignadas() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT recogidas FROM BrasaTransporteBundle:TteRecogida recogidas "
                . "LEFT JOIN recogidas.planRecogidaRel planrecogida "
                . "WHERE recogidas.estadoAsignada = 1 AND planrecogida.estadoDescargado = 0";       
        $query = $em->createQuery($dql);        
        return $query;
    }                
}